/* Leetcode #398

    Given two strings s and t which consist of only lowercase letters.

    String t is generated by random shuffling string s and then add one more letter at a random position.

    Find the letter that was added in t.
*/

public char findTheDifference(String s, String t) {
    Map<Character, Integer> mapForS = new HashMap<>();
    for (int i = 0; i < s.length(); i++) {
        char stringChar = s.charAt(i);
        if (mapForS.containsKey(stringChar)) {
            mapForS.put(stringChar, mapForS.get(stringChar) + 1);
        }
        else {
            mapForS.put(stringChar, 1);
        }
    }
    for (int i = 0; i < t.length(); i++) {
        char tChar = t.charAt(i);
        if (!mapForS.containsKey(tChar)) {
            return tChar;
        } else if (mapForS.get(tChar) > 1) {
            mapForS.put(tChar, mapForS.get(tChar) - 1); 
        } else if (mapForS.get(tChar) == 1) {
            mapForS.remove(tChar); 
        }
    }
    return 'a';
    
}